name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true
    - name: Install deps
      run: |
        npm install -g mermaid.cli
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "NO_PUSH=--no-push" >> $GITHUB_ENV
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV
    - name: Fix permission
      run: |
        chmod a+x bin/*
        git add bin/*
        git diff-index --quiet HEAD || git commit -m "add execute permission to bin/deploy"
    - name: Deploy website
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git push https://oauth-token:${{ secrets.GITHUB_TOKEN }}@github.com/preritt/preritt.github.io.git $DEPLOY_BRANCH